api_rest:
    type: rest
    resource: '../../src/Controller/'
    prefix: /api

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }